
Atividade 01 - 07/04/2024



Dados Numéricos


In [2]:
# Variável inteira
a = 1 #da o valor para a variável
print('Valor de a = '+str(a)) #print é a função que imprime a mensagem especificada na tela
type(a) #type é a função que retorna o tipo do objeto ou retorna um novo tipo de objeto baseado nas informações passadas anteriormente


Valor de a = 1


int

In [69]:
# Variável dupla precisão
b = 1.0 #agora uma variável onde o numero não é inteiro, adicionamos o ponto para fazer essa separação da parte inteira e decimal
print(b)
type(b)

1.0


float

In [4]:
# Converter float para int
c = int(b) #int converte uo valor especificado em um numero inteiro 
print(c)
type(c)

1


int

In [5]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

nan


float

In [6]:
# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
1.0


Dados de Texto


In [9]:
# Declaração de variável texto
f = 'Ezequiel'
g = 'Roberto'
print(f)
print(g)
print(f+g)
print(f+' '+g) #usa ' ' para separar o f + g

Ezequiel
Roberto
EzequielRoberto
Ezequiel Roberto


Dados tipo bool - lógica

In [10]:
a == 1 #== é usado para comparar valores de objetos, podendo resultar em true ou false

True

In [11]:
h = (a==1)
print(h)
type(h)

True


bool

In [12]:
i = True
type(i)

bool

In [13]:
ii = 'True'
type(ii)

str

Operação de comparação

In [70]:
# Operação ==
a==b #comparou os valores estabelecidos anteriormente e ambos são 1, por isso a resposta foi true

True

In [71]:
# Operação ><
a>b #como tem os mesmos valores, a não é maior que b logo é false

False

In [72]:
# Operação !=
a!=b #!= significa "diferente de" mas como são valores iguais, a resposta é false

False

In [73]:
# Operação >= ou <=
a>=b #pode significar "maior ou igual a" no caso se enquadra como igual por isso a resposta "true"

True

Operações matemáticas


In [74]:
# Soma 
a+b

2.0

In [83]:
# Soma e atribui valor
ab = a+b #soma de variáveis
print("o valor da soma é "+str(ab)) #fiz um codigo diferente para usar o +str junto para treinar

o valor da soma é 2.0


In [85]:
# Multiplicação
l = a*b # Não use l como variável 
print("Não use l como nome de variável")
j = a*b #multiplicação
print(j)

Não use l como nome de variável
1.0


In [84]:
# Divisão
a/b

1.0

In [86]:
# Potencia
5**2

25

In [87]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)

22026.465794806718

In [24]:
math.exp(0)

1.0

In [88]:
math.exp(a) #pega o valor da variável de "a"

2.718281828459045

In [89]:
math.exp(-10)

4.5399929762484854e-05

In [90]:
import math as mt
mt.log(c)

0.0

In [28]:
mt.log10(100)

2.0

Listas

In [29]:
myFirstList = [1,2,3]
print(myFirstList) #da a resposta do mesmo jeito que foi escrito

[1, 2, 3]


In [98]:
# Acessando valores da lista pelo index
print(myFirstList[0])#o numero zero seria o primeiro valor representado, nesse caso o "1"
print(myFirstList[2]) #o numero dá a posição que queremos que ele represente
print(myFirstList[1])

1
3
2


In [31]:
myFirstList==a

False

In [94]:
myFirstList[0]==a #fez a comparação de myFristList[0] com "a"

True

In [33]:
mySecList = [1,a,'c'] #criou uma segunda lista
print(mySecList)

[1, 1, 'c']


In [95]:
type(mySecList) #retornou 

list

In [35]:
type(mySecList[2])

str

In [36]:
type(mySecList[1])

int

Caminhos = path


In [38]:
path = r"C:\Users\admin\Documents\ENS5174_202401"
print(path) #usamos o path para buscar o caminho de um arquivo desejado

C:Users\admin\Documents\ENS5174_202401


In [43]:
path = r"C:\Users\admin\Documents\ENS5174_202401"
print(path)

C:\Users\admin\Documents\ENS5174_202401


In [44]:
import os
# Listar arquivos na pasta
os.listdir(path) #guia de listagem de arquivo em um diretório em Python

['.git',
 '.gitignore',
 'Aula01.ipynb',
 'inputs',
 'README.md',
 'scripts',
 'venv']

In [99]:
# Selecionar primeiro arquivo listado
os.listdir(path)[0] #posição 0 está o git

'.git'

In [46]:
# Concatenando caminhos
path+"/"+os.listdir(path)[0] #unindo conteúdo de duas strings

'C:\\Users\\admin\\Documents\\ENS5174_202401/.git'

In [47]:
# Listando caminho concatenado
os.listdir(path+"/"+os.listdir(path)[0]) #listando os conteúdos juntados

['COMMIT_EDITMSG',
 'config',
 'description',
 'FETCH_HEAD',
 'HEAD',
 'hooks',
 'index',
 'info',
 'logs',
 'objects',
 'ORIG_HEAD',
 'packed-refs',
 'refs']

In [48]:
# Diretório que estou trababalhando
os.getcwd() #retorna o diretório de trabalho atual

'C:\\Users\\admin\\Documents\\ENS5174_202401\\venv\\Scripts'

In [49]:
# Mudo de diretório para o caminho 
os.chdir('C:\\Users\\admin\\Documents\\') #altera o diretório de trabalho atual para um caminho específico

In [50]:
os.getcwd()

'C:\\Users\\admin\\Documents'

In [51]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path): #if cria uma condição 
    print('diretório já existe')
else:                                        #else complementa o if
    print('Criando diretório '+new_path)
    os.mkdir(new_path)

Criando diretório C:\Users\admin\Documents/test


In [52]:
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")

Criando diretório C:\Users\admin\Documents/test2


Numpy arrays e Pandas DataFrames

In [53]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [54]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)

[ 1  2  3 10 20 55]


In [55]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10) #cria a matriz 10x10 com valores aleatórios
print(n)
# Dimensões da matrix
print(n.shape)

[[0.51707514 0.97236681 0.7394582  0.72974558 0.12281848 0.53314702
  0.83733813 0.64723194 0.95149433 0.9098236 ]
 [0.62366785 0.03069186 0.28813578 0.99216436 0.31673189 0.84239795
  0.89971734 0.25424215 0.0110261  0.66383908]
 [0.86055162 0.45362332 0.76343778 0.30176176 0.65499907 0.00937182
  0.01522104 0.56413879 0.14888022 0.81266494]
 [0.15054676 0.4658138  0.34123357 0.97193019 0.925103   0.61530634
  0.97573731 0.27551917 0.51785182 0.48855838]
 [0.19904756 0.24439994 0.96780004 0.62833659 0.31238797 0.89223995
  0.4063449  0.55151119 0.39186808 0.03267094]
 [0.56100129 0.12160452 0.17431794 0.95032675 0.4237497  0.53791292
  0.92057644 0.879277   0.56069805 0.97644704]
 [0.43383443 0.22335855 0.84847221 0.73702667 0.98720907 0.7556679
  0.49359475 0.89483154 0.90701944 0.2508256 ]
 [0.63404568 0.96215478 0.06022406 0.90328826 0.57059549 0.46767821
  0.43119413 0.8312102  0.26340941 0.01292152]
 [0.30190602 0.18472923 0.79619664 0.46165996 0.46252765 0.06023358
  0.76494747 

In [56]:
# Acessando valores da matriz
n[0,:]

array([0.51707514, 0.97236681, 0.7394582 , 0.72974558, 0.12281848,
       0.53314702, 0.83733813, 0.64723194, 0.95149433, 0.9098236 ])

In [57]:
n[:,0]

array([0.51707514, 0.62366785, 0.86055162, 0.15054676, 0.19904756,
       0.56100129, 0.43383443, 0.63404568, 0.30190602, 0.95128614])

In [58]:
n[:,1:5]

array([[0.97236681, 0.7394582 , 0.72974558, 0.12281848],
       [0.03069186, 0.28813578, 0.99216436, 0.31673189],
       [0.45362332, 0.76343778, 0.30176176, 0.65499907],
       [0.4658138 , 0.34123357, 0.97193019, 0.925103  ],
       [0.24439994, 0.96780004, 0.62833659, 0.31238797],
       [0.12160452, 0.17431794, 0.95032675, 0.4237497 ],
       [0.22335855, 0.84847221, 0.73702667, 0.98720907],
       [0.96215478, 0.06022406, 0.90328826, 0.57059549],
       [0.18472923, 0.79619664, 0.46165996, 0.46252765],
       [0.31564213, 0.40536288, 0.22173643, 0.63917273]])

In [59]:
n[0,1:5]

array([0.97236681, 0.7394582 , 0.72974558, 0.12281848])

In [60]:
n[0,-1]

0.9098236026635861

In [61]:
n[0,4:-1]

array([0.12281848, 0.53314702, 0.83733813, 0.64723194, 0.95149433])

In [62]:
n[0,4:]

array([0.12281848, 0.53314702, 0.83733813, 0.64723194, 0.95149433,
       0.9098236 ])

In [63]:
an = np.log(n*5)
print(an)

[[ 0.94987083  1.58141575  1.30760039  1.29437859 -0.48760987  0.98047985
   1.4319106   1.17438734  1.55971636  1.51493337]
 [ 1.13730057 -1.87432005  0.36511447  1.60157141  0.45973827  1.43793516
   1.50376328  0.23996979 -2.89805244  1.19972241]
 [ 1.45925624  0.81894979  1.33951426  0.41132045  1.18631645 -3.06060959
  -2.57563841  1.03698294 -0.29517529  1.40200153]
 [-0.28404366  0.84546861  0.53424982  1.58096662  1.53158771  1.12380288
   1.58487604  0.32033985  0.95137176  0.89314162]
 [-0.00477355  0.20048861  1.57670812  1.14475863  0.44592855  1.49541773
   0.70888494  1.01434475  0.6726079  -1.81183146]
 [ 1.03140585 -0.49754321 -0.1374365   1.55848851  0.75082559  0.98937933
   1.52668268  1.48078261  1.03086516  1.58560315]
 [ 0.7743456   0.11046097  1.44511997  1.30430671  1.59656448  1.32928463
   0.90339746  1.49831811  1.51184652  0.22644051]
 [ 1.15380364  1.57085797 -1.20024551  1.50772437  1.04836316  0.84946311
   0.76824103  1.42456535  0.27539216 -2.73942315]
